version: '3.9'

services:
  cloudflared:
    image: cloudflare/cloudflared:2026.10.0@sha256:9b49eed8f62806d5d45ddf59ecefb5710429598ea6d3fcccd2af938f621b2b07
    hostname: cloudflared
    container_name: konomitv__cloudflared

    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m
